name: Publish Report Example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  test:
    name: Deploy HTML report example
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      # --- HTML example deployment ---
      - name: Rename entry point of report to index.html
        run: |
          mv quarto_report/quarto_report.html quarto_report/index.html
      - name: Publish HTML report to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: quarto_report/
